name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0
          sudo apt-get install -y libxkbcommon-x11-0
          sudo apt-get install -y libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xfixes0
          sudo apt-get install -y libcanberra-gtk-module

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 pyinstaller requests cx_Freeze pillow

      - name: Build executable
        run: |
          pyinstaller launcher.py --onefile --name epic_launcher

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/epic_launcher
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 